/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios/route'
import { Route as NegocioRouteImport } from './routes/negocio/route'
import { Route as completeRouteImport } from './routes/(complete)/route'
import { Route as IndexImport } from './routes/index'
import { Route as UsuariosRegistroImport } from './routes/usuarios/registro'
import { Route as UsuariosLoginImport } from './routes/usuarios/login'
import { Route as completeCompletarRegistroImport } from './routes/(complete)/completar-registro'
import { Route as UsuariosDashboardRouteImport } from './routes/usuarios/dashboard/route'
import { Route as NegocioDashboardRouteImport } from './routes/negocio/dashboard/route'
import { Route as NegocioauthRouteImport } from './routes/negocio/(auth)/route'
import { Route as NegocioDashboardMascotasImport } from './routes/negocio/dashboard/mascotas'
import { Route as NegocioDashboardInicioImport } from './routes/negocio/dashboard/inicio'
import { Route as NegocioauthRegistrateImport } from './routes/negocio/(auth)/registrate'
import { Route as NegocioauthOlvideMiContrasenaImport } from './routes/negocio/(auth)/olvide-mi-contrasena'
import { Route as NegocioauthLoginImport } from './routes/negocio/(auth)/login'

// Create/Update Routes

const UsuariosRouteRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRoute,
} as any)

const NegocioRouteRoute = NegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => rootRoute,
} as any)

const completeRouteRoute = completeRouteImport.update({
  id: '/(complete)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsuariosRegistroRoute = UsuariosRegistroImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => UsuariosRouteRoute,
} as any)

const UsuariosLoginRoute = UsuariosLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UsuariosRouteRoute,
} as any)

const completeCompletarRegistroRoute = completeCompletarRegistroImport.update({
  id: '/completar-registro',
  path: '/completar-registro',
  getParentRoute: () => completeRouteRoute,
} as any)

const UsuariosDashboardRouteRoute = UsuariosDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UsuariosRouteRoute,
} as any)

const NegocioDashboardRouteRoute = NegocioDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NegocioRouteRoute,
} as any)

const NegocioauthRouteRoute = NegocioauthRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => NegocioRouteRoute,
} as any)

const NegocioDashboardMascotasRoute = NegocioDashboardMascotasImport.update({
  id: '/mascotas',
  path: '/mascotas',
  getParentRoute: () => NegocioDashboardRouteRoute,
} as any)

const NegocioDashboardInicioRoute = NegocioDashboardInicioImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => NegocioDashboardRouteRoute,
} as any)

const NegocioauthRegistrateRoute = NegocioauthRegistrateImport.update({
  id: '/registrate',
  path: '/registrate',
  getParentRoute: () => NegocioauthRouteRoute,
} as any)

const NegocioauthOlvideMiContrasenaRoute =
  NegocioauthOlvideMiContrasenaImport.update({
    id: '/olvide-mi-contrasena',
    path: '/olvide-mi-contrasena',
    getParentRoute: () => NegocioauthRouteRoute,
  } as any)

const NegocioauthLoginRoute = NegocioauthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NegocioauthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(complete)': {
      id: '/(complete)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof completeRouteImport
      parentRoute: typeof rootRoute
    }
    '/negocio': {
      id: '/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof NegocioRouteImport
      parentRoute: typeof rootRoute
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRoute
    }
    '/negocio/(auth)': {
      id: '/negocio/(auth)'
      path: '/'
      fullPath: '/negocio/'
      preLoaderRoute: typeof NegocioauthRouteImport
      parentRoute: typeof NegocioRouteImport
    }
    '/negocio/dashboard': {
      id: '/negocio/dashboard'
      path: '/dashboard'
      fullPath: '/negocio/dashboard'
      preLoaderRoute: typeof NegocioDashboardRouteImport
      parentRoute: typeof NegocioRouteImport
    }
    '/usuarios/dashboard': {
      id: '/usuarios/dashboard'
      path: '/dashboard'
      fullPath: '/usuarios/dashboard'
      preLoaderRoute: typeof UsuariosDashboardRouteImport
      parentRoute: typeof UsuariosRouteImport
    }
    '/(complete)/completar-registro': {
      id: '/(complete)/completar-registro'
      path: '/completar-registro'
      fullPath: '/completar-registro'
      preLoaderRoute: typeof completeCompletarRegistroImport
      parentRoute: typeof completeRouteImport
    }
    '/usuarios/login': {
      id: '/usuarios/login'
      path: '/login'
      fullPath: '/usuarios/login'
      preLoaderRoute: typeof UsuariosLoginImport
      parentRoute: typeof UsuariosRouteImport
    }
    '/usuarios/registro': {
      id: '/usuarios/registro'
      path: '/registro'
      fullPath: '/usuarios/registro'
      preLoaderRoute: typeof UsuariosRegistroImport
      parentRoute: typeof UsuariosRouteImport
    }
    '/negocio/(auth)/login': {
      id: '/negocio/(auth)/login'
      path: '/login'
      fullPath: '/negocio/login'
      preLoaderRoute: typeof NegocioauthLoginImport
      parentRoute: typeof NegocioauthRouteImport
    }
    '/negocio/(auth)/olvide-mi-contrasena': {
      id: '/negocio/(auth)/olvide-mi-contrasena'
      path: '/olvide-mi-contrasena'
      fullPath: '/negocio/olvide-mi-contrasena'
      preLoaderRoute: typeof NegocioauthOlvideMiContrasenaImport
      parentRoute: typeof NegocioauthRouteImport
    }
    '/negocio/(auth)/registrate': {
      id: '/negocio/(auth)/registrate'
      path: '/registrate'
      fullPath: '/negocio/registrate'
      preLoaderRoute: typeof NegocioauthRegistrateImport
      parentRoute: typeof NegocioauthRouteImport
    }
    '/negocio/dashboard/inicio': {
      id: '/negocio/dashboard/inicio'
      path: '/inicio'
      fullPath: '/negocio/dashboard/inicio'
      preLoaderRoute: typeof NegocioDashboardInicioImport
      parentRoute: typeof NegocioDashboardRouteImport
    }
    '/negocio/dashboard/mascotas': {
      id: '/negocio/dashboard/mascotas'
      path: '/mascotas'
      fullPath: '/negocio/dashboard/mascotas'
      preLoaderRoute: typeof NegocioDashboardMascotasImport
      parentRoute: typeof NegocioDashboardRouteImport
    }
  }
}

// Create and export the route tree

interface completeRouteRouteChildren {
  completeCompletarRegistroRoute: typeof completeCompletarRegistroRoute
}

const completeRouteRouteChildren: completeRouteRouteChildren = {
  completeCompletarRegistroRoute: completeCompletarRegistroRoute,
}

const completeRouteRouteWithChildren = completeRouteRoute._addFileChildren(
  completeRouteRouteChildren,
)

interface NegocioauthRouteRouteChildren {
  NegocioauthLoginRoute: typeof NegocioauthLoginRoute
  NegocioauthOlvideMiContrasenaRoute: typeof NegocioauthOlvideMiContrasenaRoute
  NegocioauthRegistrateRoute: typeof NegocioauthRegistrateRoute
}

const NegocioauthRouteRouteChildren: NegocioauthRouteRouteChildren = {
  NegocioauthLoginRoute: NegocioauthLoginRoute,
  NegocioauthOlvideMiContrasenaRoute: NegocioauthOlvideMiContrasenaRoute,
  NegocioauthRegistrateRoute: NegocioauthRegistrateRoute,
}

const NegocioauthRouteRouteWithChildren =
  NegocioauthRouteRoute._addFileChildren(NegocioauthRouteRouteChildren)

interface NegocioDashboardRouteRouteChildren {
  NegocioDashboardInicioRoute: typeof NegocioDashboardInicioRoute
  NegocioDashboardMascotasRoute: typeof NegocioDashboardMascotasRoute
}

const NegocioDashboardRouteRouteChildren: NegocioDashboardRouteRouteChildren = {
  NegocioDashboardInicioRoute: NegocioDashboardInicioRoute,
  NegocioDashboardMascotasRoute: NegocioDashboardMascotasRoute,
}

const NegocioDashboardRouteRouteWithChildren =
  NegocioDashboardRouteRoute._addFileChildren(
    NegocioDashboardRouteRouteChildren,
  )

interface NegocioRouteRouteChildren {
  NegocioauthRouteRoute: typeof NegocioauthRouteRouteWithChildren
  NegocioDashboardRouteRoute: typeof NegocioDashboardRouteRouteWithChildren
}

const NegocioRouteRouteChildren: NegocioRouteRouteChildren = {
  NegocioauthRouteRoute: NegocioauthRouteRouteWithChildren,
  NegocioDashboardRouteRoute: NegocioDashboardRouteRouteWithChildren,
}

const NegocioRouteRouteWithChildren = NegocioRouteRoute._addFileChildren(
  NegocioRouteRouteChildren,
)

interface UsuariosRouteRouteChildren {
  UsuariosDashboardRouteRoute: typeof UsuariosDashboardRouteRoute
  UsuariosLoginRoute: typeof UsuariosLoginRoute
  UsuariosRegistroRoute: typeof UsuariosRegistroRoute
}

const UsuariosRouteRouteChildren: UsuariosRouteRouteChildren = {
  UsuariosDashboardRouteRoute: UsuariosDashboardRouteRoute,
  UsuariosLoginRoute: UsuariosLoginRoute,
  UsuariosRegistroRoute: UsuariosRegistroRoute,
}

const UsuariosRouteRouteWithChildren = UsuariosRouteRoute._addFileChildren(
  UsuariosRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof completeRouteRouteWithChildren
  '/negocio': typeof NegocioRouteRouteWithChildren
  '/usuarios': typeof UsuariosRouteRouteWithChildren
  '/negocio/': typeof NegocioauthRouteRouteWithChildren
  '/negocio/dashboard': typeof NegocioDashboardRouteRouteWithChildren
  '/usuarios/dashboard': typeof UsuariosDashboardRouteRoute
  '/completar-registro': typeof completeCompletarRegistroRoute
  '/usuarios/login': typeof UsuariosLoginRoute
  '/usuarios/registro': typeof UsuariosRegistroRoute
  '/negocio/login': typeof NegocioauthLoginRoute
  '/negocio/olvide-mi-contrasena': typeof NegocioauthOlvideMiContrasenaRoute
  '/negocio/registrate': typeof NegocioauthRegistrateRoute
  '/negocio/dashboard/inicio': typeof NegocioDashboardInicioRoute
  '/negocio/dashboard/mascotas': typeof NegocioDashboardMascotasRoute
}

export interface FileRoutesByTo {
  '/': typeof completeRouteRouteWithChildren
  '/usuarios': typeof UsuariosRouteRouteWithChildren
  '/negocio': typeof NegocioauthRouteRouteWithChildren
  '/negocio/dashboard': typeof NegocioDashboardRouteRouteWithChildren
  '/usuarios/dashboard': typeof UsuariosDashboardRouteRoute
  '/completar-registro': typeof completeCompletarRegistroRoute
  '/usuarios/login': typeof UsuariosLoginRoute
  '/usuarios/registro': typeof UsuariosRegistroRoute
  '/negocio/login': typeof NegocioauthLoginRoute
  '/negocio/olvide-mi-contrasena': typeof NegocioauthOlvideMiContrasenaRoute
  '/negocio/registrate': typeof NegocioauthRegistrateRoute
  '/negocio/dashboard/inicio': typeof NegocioDashboardInicioRoute
  '/negocio/dashboard/mascotas': typeof NegocioDashboardMascotasRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(complete)': typeof completeRouteRouteWithChildren
  '/negocio': typeof NegocioRouteRouteWithChildren
  '/usuarios': typeof UsuariosRouteRouteWithChildren
  '/negocio/(auth)': typeof NegocioauthRouteRouteWithChildren
  '/negocio/dashboard': typeof NegocioDashboardRouteRouteWithChildren
  '/usuarios/dashboard': typeof UsuariosDashboardRouteRoute
  '/(complete)/completar-registro': typeof completeCompletarRegistroRoute
  '/usuarios/login': typeof UsuariosLoginRoute
  '/usuarios/registro': typeof UsuariosRegistroRoute
  '/negocio/(auth)/login': typeof NegocioauthLoginRoute
  '/negocio/(auth)/olvide-mi-contrasena': typeof NegocioauthOlvideMiContrasenaRoute
  '/negocio/(auth)/registrate': typeof NegocioauthRegistrateRoute
  '/negocio/dashboard/inicio': typeof NegocioDashboardInicioRoute
  '/negocio/dashboard/mascotas': typeof NegocioDashboardMascotasRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/negocio'
    | '/usuarios'
    | '/negocio/'
    | '/negocio/dashboard'
    | '/usuarios/dashboard'
    | '/completar-registro'
    | '/usuarios/login'
    | '/usuarios/registro'
    | '/negocio/login'
    | '/negocio/olvide-mi-contrasena'
    | '/negocio/registrate'
    | '/negocio/dashboard/inicio'
    | '/negocio/dashboard/mascotas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/usuarios'
    | '/negocio'
    | '/negocio/dashboard'
    | '/usuarios/dashboard'
    | '/completar-registro'
    | '/usuarios/login'
    | '/usuarios/registro'
    | '/negocio/login'
    | '/negocio/olvide-mi-contrasena'
    | '/negocio/registrate'
    | '/negocio/dashboard/inicio'
    | '/negocio/dashboard/mascotas'
  id:
    | '__root__'
    | '/'
    | '/(complete)'
    | '/negocio'
    | '/usuarios'
    | '/negocio/(auth)'
    | '/negocio/dashboard'
    | '/usuarios/dashboard'
    | '/(complete)/completar-registro'
    | '/usuarios/login'
    | '/usuarios/registro'
    | '/negocio/(auth)/login'
    | '/negocio/(auth)/olvide-mi-contrasena'
    | '/negocio/(auth)/registrate'
    | '/negocio/dashboard/inicio'
    | '/negocio/dashboard/mascotas'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  completeRouteRoute: typeof completeRouteRouteWithChildren
  NegocioRouteRoute: typeof NegocioRouteRouteWithChildren
  UsuariosRouteRoute: typeof UsuariosRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  completeRouteRoute: completeRouteRouteWithChildren,
  NegocioRouteRoute: NegocioRouteRouteWithChildren,
  UsuariosRouteRoute: UsuariosRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(complete)",
        "/negocio",
        "/usuarios"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(complete)": {
      "filePath": "(complete)/route.tsx",
      "children": [
        "/(complete)/completar-registro"
      ]
    },
    "/negocio": {
      "filePath": "negocio/route.tsx",
      "children": [
        "/negocio/(auth)",
        "/negocio/dashboard"
      ]
    },
    "/usuarios": {
      "filePath": "usuarios/route.tsx",
      "children": [
        "/usuarios/dashboard",
        "/usuarios/login",
        "/usuarios/registro"
      ]
    },
    "/negocio/(auth)": {
      "filePath": "negocio/(auth)/route.tsx",
      "parent": "/negocio",
      "children": [
        "/negocio/(auth)/login",
        "/negocio/(auth)/olvide-mi-contrasena",
        "/negocio/(auth)/registrate"
      ]
    },
    "/negocio/dashboard": {
      "filePath": "negocio/dashboard/route.tsx",
      "parent": "/negocio",
      "children": [
        "/negocio/dashboard/inicio",
        "/negocio/dashboard/mascotas"
      ]
    },
    "/usuarios/dashboard": {
      "filePath": "usuarios/dashboard/route.tsx",
      "parent": "/usuarios"
    },
    "/(complete)/completar-registro": {
      "filePath": "(complete)/completar-registro.tsx",
      "parent": "/(complete)"
    },
    "/usuarios/login": {
      "filePath": "usuarios/login.tsx",
      "parent": "/usuarios"
    },
    "/usuarios/registro": {
      "filePath": "usuarios/registro.tsx",
      "parent": "/usuarios"
    },
    "/negocio/(auth)/login": {
      "filePath": "negocio/(auth)/login.tsx",
      "parent": "/negocio/(auth)"
    },
    "/negocio/(auth)/olvide-mi-contrasena": {
      "filePath": "negocio/(auth)/olvide-mi-contrasena.tsx",
      "parent": "/negocio/(auth)"
    },
    "/negocio/(auth)/registrate": {
      "filePath": "negocio/(auth)/registrate.tsx",
      "parent": "/negocio/(auth)"
    },
    "/negocio/dashboard/inicio": {
      "filePath": "negocio/dashboard/inicio.tsx",
      "parent": "/negocio/dashboard"
    },
    "/negocio/dashboard/mascotas": {
      "filePath": "negocio/dashboard/mascotas.tsx",
      "parent": "/negocio/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
